data = {
  "toggle-btn-1": {
    html: [
      '&lt;label class="toggle-btn-1"&gt;\n',
      '&nbsp;&nbsp;&lt;input type="checkbox" /&gt;\n',
      '&nbsp;&nbsp;&lt;span class="circle"&gt;&lt;/span&gt;\n',
      "&lt;/label&gt;",
    ],

    css: [
      "*,\n",
      "::before,\n",
      "::after{\n",
      "&nbsp;&nbsp;margin:0;\n",
      "&nbsp;&nbsp;padding:0;\n",
      "&nbsp;&nbsp;box-sizing:border-box;\n",
      "}\n",
      ".toggle-btn-1 {\n",
      "&nbsp;&nbsp;width: 150px;\n",
      "&nbsp;&nbsp;height: 50px;\n",
      "&nbsp;&nbsp;position: relative;\n",
      "&nbsp;&nbsp;display: inline-block;\n",
      "}\n",
      '.toggle-btn-1 input[type="checkbox"] {\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;box-shadow: 10px 10px 20px 0 rgba(0, 0, 0, 0.2),\n",
      "&nbsp;&nbsp; -10px -10px 20px 0 rgba(255, 255, 255, 0.5);\n",
      "&nbsp;&nbsp;appearance: none;\n",
      "&nbsp;&nbsp;-webkit-appearance: none;\n",
      "&nbsp;&nbsp;-moz-appearance: none;\n",
      "&nbsp;&nbsp;cursor: pointer;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;outline: none;\n",
      "}\n",
      ".toggle-btn-1 .circle {\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 45px;\n",
      "&nbsp;&nbsp;height: 45px;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 5px;\n",
      "&nbsp;&nbsp;transform: translateY(-50%);\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;box-shadow: 1px 1px 10px 0 #5ab9ea inset,\n",
      "&nbsp;&nbsp;-5px -5px 20px 0 #5ab9ea inset;\n",
      "&nbsp;&nbsp;transition: all 450ms ease-in-out;\n",
      "&nbsp;&nbsp;pointer-events: none;\n",
      "}\n",
      ".toggle-btn-1 .circle::before {\n",
      '&nbsp;&nbsp;content: "OFF";\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 50%;\n",
      "&nbsp;&nbsp;transform: translate(-50%, -50%);\n",
      "&nbsp;&nbsp;font-family: monospace;\n",
      "&nbsp;&nbsp;font-size: 1.15rem;\n",
      "}\n",
      '.toggle-btn-1 input[type="checkbox"]:checked {\n',
      "&nbsp;&nbsp;box-shadow: inset 6px 6px 10px 0 rgba(0, 0, 0, 0.2),\n",
      "&nbsp;&nbsp;inset -6px -6px 10px 0 rgba(255, 255, 255, 0.5);\n",
      "}\n",
      '.toggle-btn-1 input[type="checkbox"]:checked ~ .circle {\n',
      "&nbsp;&nbsp;box-shadow: 1px 1px 10px 0 #6bea5a inset, -5px -5px 20px 0 #6bea5a inset;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;left: 100px;\n",
      "&nbsp;&nbsp;transform: translateY(-50%) rotate(360deg);\n",
      "}\n",
      '.toggle-btn-1 input[type="checkbox"]:checked ~ .circle::before {\n',
      '&nbsp;&nbsp;content: "ON";\n',
      "}\n",
    ],
  },
  "toggle-btn-2": {
    html: [
      '&lt;label class="toggle-btn-2"&gt;\n',
      '&nbsp;&nbsp;&lt;input type="checkbox" /&gt;\n',
      '&nbsp;&nbsp;&lt;span class="circle"&gt;&lt;/span&gt;\n',
      "&lt;/label&gt;",
    ],

    css: [
      "*,\n",
      "::before,\n",
      "::after{\n",
      "&nbsp;&nbsp;margin:0;\n",
      "&nbsp;&nbsp;padding:0;\n",
      "&nbsp;&nbsp;box-sizing:border-box;\n",
      "}\n",
      ".toggle-btn-2 {\n",
      "&nbsp;&nbsp;width: 150px;\n",
      "&nbsp;&nbsp;height: 50px;\n",
      "&nbsp;&nbsp;position: relative;\n",
      "&nbsp;&nbsp;display: inline-block;\n",
      "}\n",
      '.toggle-btn-2 input[type="checkbox"] {\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);\n",
      "&nbsp;&nbsp;appearance: none;\n",
      "&nbsp;&nbsp;-webkit-appearance: none;\n",
      "&nbsp;&nbsp;-moz-appearance: none;\n",
      "&nbsp;&nbsp;cursor: pointer;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;outline: none;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "}\n",
      ".toggle-btn-2 .circle {\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 35px;\n",
      "&nbsp;&nbsp;height: 35px;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 10px;\n",
      "&nbsp;&nbsp;transform: translateY(-50%);\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "&nbsp;&nbsp;background-color: #000;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;pointer-events: none;\n",
      "}\n",
      ".toggle-btn-2 .circle::before {\n",
      '&nbsp;&nbsp;content: "";\n',
      "&nbsp;&nbsp;width: 50%;\n",
      "&nbsp;&nbsp;height: 50%;",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 50%;\n",
      "&nbsp;&nbsp;transform: translate(-50%, -50%);\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;transition-delay: 100ms;\n",
      "}\n",
      '.toggle-btn-2 input[type="checkbox"]:checked {\n',
      "&nbsp;&nbsp;background-color: #000;\n",
      "}\n",
      '.toggle-btn-2 input[type="checkbox"]:checked ~ .circle {\n',
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;left: 105px;\n",
      "}\n",
      '.toggle-btn-2 input[type="checkbox"]:checked ~ .circle::before {\n',
      "&nbsp;&nbsp;width: 25%;\n",
      "&nbsp;&nbsp;border-radius: 10px;\n",
      "&nbsp;&nbsp;background-color: #000;\n",
      "}\n",
    ],
  },
  "toggle-btn-3": {
    html: [
      '&lt;label class="toggle-btn-3"&gt;\n',
      '&nbsp;&nbsp;&lt;input type="checkbox" /&gt;\n',
      '&nbsp;&nbsp;&lt;span class="toggle-text"&gt;&lt;/span&gt;\n',
      "&lt;/label&gt;",
    ],

    css: [
      "*,\n",
      "::before,\n",
      "::after{\n",
      "&nbsp;&nbsp;margin:0;\n",
      "&nbsp;&nbsp;padding:0;\n",
      "&nbsp;&nbsp;box-sizing:border-box;\n",
      "}\n",
      ".toggle-btn-3 {\n",
      "&nbsp;&nbsp;width: 160px;\n",
      "&nbsp;&nbsp;height: 45px;\n",
      "&nbsp;&nbsp;position: relative;\n",
      "&nbsp;&nbsp;display: inline-block;\n",
      "}\n",
      '.toggle-btn-3 input[type="checkbox"] {\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);\n",
      "&nbsp;&nbsp;appearance: none;\n",
      "&nbsp;&nbsp;-webkit-appearance: none;\n",
      "&nbsp;&nbsp;-moz-appearance: none;\n",
      "&nbsp;&nbsp;cursor: pointer;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;outline: none;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;z-index: 1;\n",
      "&nbsp;&nbsp;overflow: hidden;\n",
      "}\n",
      '.toggle-btn-3 input[type="checkbox"]::before {\n',
      '&nbsp;&nbsp;content: "";\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 0;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;background-color: #733337;\n",
      "&nbsp;&nbsp;left: 0;\n",
      "&nbsp;&nbsp;top: 0;\n",
      "&nbsp;&nbsp;z-index: -1;\n",
      "&nbsp;&nbsp;transition: width 300ms ease-in-out;\n",
      "}\n",
      ".toggle-btn-3 .toggle-text {\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 40px;\n",
      "&nbsp;&nbsp;height: 20px;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 10px;\n",
      "&nbsp;&nbsp;transform: translateY(-50%);\n",
      "&nbsp;&nbsp;background-color: transparent;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;pointer-events: none;\n",
      "&nbsp;&nbsp;z-index: 1;\n",
      "}\n",
      ".toggle-btn-3 .toggle-text::before {\n",
      '&nbsp;&nbsp;content: "OFF";\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;color: #733337;\n",
      "&nbsp;&nbsp;text-align: center;\n",
      "&nbsp;&nbsp;font-weight: 700;\n",
      "&nbsp;&nbsp;font-size: 1.15rem;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;transition-delay: 100ms;\n",
      "&nbsp;&nbsp;font-family:sans-serif;\n",
      "}\n",
      '.toggle-btn-3 input[type="checkbox"]:checked::before {\n',
      "&nbsp;&nbsp;width: 100%;\n",
      "}\n",
      '.toggle-btn-3 input[type="checkbox"]:checked ~ .toggle-text {\n',
      "&nbsp;&nbsp;left: 110px;\n",
      "}\n",
      '.toggle-btn-3 input[type="checkbox"]:checked ~ .toggle-text::before {\n',
      '&nbsp;&nbsp;content: "ON";\n',
      "&nbsp;&nbsp;color: #fff;\n",
      "}\n",
    ],
  },
  "toggle-btn-4": {
    html: [
      '&lt;label class="toggle-btn-4 toggle"&gt;\n',
      '&nbsp;&nbsp;&lt;input type="checkbox" /&gt;\n',
      '&nbsp;&nbsp;&lt;span class="circle"&gt;&lt;/span&gt;\n',
      "&lt;/label&gt;",
    ],

    css: [
      "*,\n",
      "::before,\n",
      "::after{\n",
      "&nbsp;&nbsp;margin:0;\n",
      "&nbsp;&nbsp;padding:0;\n",
      "&nbsp;&nbsp;box-sizing:border-box;\n",
      "}\n",
      ".toggle-btn-4 {\n",
      "&nbsp;&nbsp;width: 150px;\n",
      "&nbsp;&nbsp;height: 50px;\n",
      "&nbsp;&nbsp;position: relative;\n",
      "&nbsp;&nbsp;display: inline-block;\n",
      "}\n",
      '.toggle-btn-4 input[type="checkbox"] {\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);\n",
      "&nbsp;&nbsp;appearance: none;\n",
      "&nbsp;&nbsp;-webkit-appearance: none;\n",
      "&nbsp;&nbsp;-moz-appearance: none;\n",
      "&nbsp;&nbsp;cursor: pointer;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;outline: none;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "}\n",
      ".toggle-btn-4 .circle {\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 35px;\n",
      "&nbsp;&nbsp;height: 35px;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;left: 10px;\n",
      "&nbsp;&nbsp;transform: translateY(-50%);\n",
      "&nbsp;&nbsp;background-color: transparent;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;pointer-events: none;\n",
      "&nbsp;&nbsp;border: 8px solid #0d4f8b;\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "}\n",
      ".toggle-btn-4 .circle::before {\n",
      '&nbsp;&nbsp;content: "";\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 60%;\n",
      "&nbsp;&nbsp;height: 80%;\n",
      "&nbsp;&nbsp;top: -2px;\n",
      "&nbsp;&nbsp;left: 0;\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "&nbsp;&nbsp;transform: rotate(30deg) scale(0);\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;transition-delay: 50ms;\n",
      "}\n",
      '.toggle-btn-4 input[type="checkbox"]:checked {\n',
      "&nbsp;&nbsp;background-color: #0d4f8b;\n",
      "}\n",
      '.toggle-btn-4 input[type="checkbox"]:checked ~ .circle {\n',
      "&nbsp;&nbsp;left: 105px;\n",
      "&nbsp;&nbsp;border: 0;\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "}\n",
      '.toggle-btn-4 input[type="checkbox"]:checked ~ .circle::before {\n',
      "&nbsp;&nbsp;background-color: #0d4f8b;\n",
      "&nbsp;&nbsp;transform: rotate(30deg) scale(1);\n",
      "}\n",
    ],
  },
  "toggle-btn-5": {
    html: [
      '&lt;label class="toggle-btn-5 toggle"&gt;\n',
      '&nbsp;&nbsp;&lt;input type="checkbox" /&gt;\n',
      '&nbsp;&nbsp;&lt;span class="circle left-circle"&gt;&lt;/span&gt;\n',
      '&nbsp;&nbsp;&lt;span class="circle right-circle"&gt;&lt;/span&gt;\n',
      "&lt;/label&gt;",
    ],

    css: [
      "*,\n",
      "::before,\n",
      "::after{\n",
      "&nbsp;&nbsp;margin:0;\n",
      "&nbsp;&nbsp;padding:0;\n",
      "&nbsp;&nbsp;box-sizing:border-box;\n",
      "}\n",
      ".toggle-btn-5 {\n",
      "&nbsp;&nbsp;width: 150px;\n",
      "&nbsp;&nbsp;height: 50px;\n",
      "&nbsp;&nbsp;position: relative;\n",
      "&nbsp;&nbsp;display: inline-block;\n",
      "}\n",
      '.toggle-btn-5 input[type="checkbox"] {\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 100%;\n",
      "&nbsp;&nbsp;height: 100%;\n",
      "&nbsp;&nbsp;border-radius: 30px;\n",
      "&nbsp;&nbsp;box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.2);\n",
      "&nbsp;&nbsp;appearance: none;\n",
      "&nbsp;&nbsp;-webkit-appearance: none;\n",
      "&nbsp;&nbsp;-moz-appearance: none;\n",
      "&nbsp;&nbsp;cursor: pointer;\n",
      "&nbsp;&nbsp;transition: all 300ms ease-in-out;\n",
      "&nbsp;&nbsp;outline: none;\n",
      "&nbsp;&nbsp;background-color: #ff7441;\n",
      "&nbsp;&nbsp;overflow: hidden;\n",
      "}\n",
      '.toggle-btn-5 input[type="checkbox"]::before {\n',
      '&nbsp;&nbsp;content: "";\n',
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 120%;\n",
      "&nbsp;&nbsp;height: 200%;\n",
      "&nbsp;&nbsp;left: 50%;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;transform: translate(-50%, -50%) scale(0);\n",
      "&nbsp;&nbsp;transform-origin: 0 50%;\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "&nbsp;&nbsp;background-color: #78ca20;\n",
      "&nbsp;&nbsp;transition: all 450ms ease-in-out;\n",
      "}\n",
      ".toggle-btn-5 .circle {\n",
      "&nbsp;&nbsp;position: absolute;\n",
      "&nbsp;&nbsp;width: 25px;\n",
      "&nbsp;&nbsp;height: 25px;\n",
      "&nbsp;&nbsp;top: 50%;\n",
      "&nbsp;&nbsp;transform: translateY(-50%);\n",
      "&nbsp;&nbsp;background-color: #fff;\n",
      "&nbsp;&nbsp;transition: all 450ms ease-in-out;\n",
      "&nbsp;&nbsp;pointer-events: none;\n",
      "&nbsp;&nbsp;border-radius: 50%;\n",
      "}\n",
      ".toggle-btn-5 .left-circle {\n",
      "&nbsp;&nbsp;left: 10px;\n",
      "}\n",
      ".toggle-btn-5 .right-circle {\n",
      "&nbsp;&nbsp;left: 115px;\n",
      "&nbsp;&nbsp;background-color: #ff7441;\n",
      "}\n",
      '.toggle-btn-5 input[type="checkbox"]:checked::before {\n',
      "&nbsp;&nbsp;transform: translate(-50%, -50%) scale(1);\n",
      "}\n",
      '.toggle-btn-5 input[type="checkbox"]:checked ~ .left-circle {\n',
      "&nbsp;&nbsp;background: #78ca20;\n",
      "}\n",
      '.toggle-btn-5 input[type="checkbox"]:checked ~ .right-circle {\n',
      "&nbsp;&nbsp;background: #fff;\n",
      "}\n",
    ],
  },
};
